from pathlib import Path
p=Path('index.html')
s=p.read_text()
start=s.index('function best(')
end=s.index("$('go').onclick", start)
new=r'''function scorePair(b,l){let ex=Math.abs(b.amt-l.amt)<.01,g=gap(b.d,l.d),ds=sim(b.desc,l.desc),rf=b.ref&&l.ref&&norm(b.ref)===norm(l.ref);return (ex?55:0)+(rf?30:0)+ds*15+(g===0?15:g<=7?Math.max(0,15-g*2):0)}
function best(b,used){let bi=-1,bs=-1;S.ledger.forEach((l,i)=>{if(used.has(i))return;let s=scorePair(b,l);if(s>bs){bs=s;bi=i}});return{bi,bs}}
function feeLike(s){return /\b(vat|vat fee|nip fee|stamp duty|processing fee|process(?:ing)? charge|bank charge|charges|fee|fees|sms notification|rtgs|remita|commission|comm\s*chrg|amf|levy|tax)\b/i.test(String(s||''))}
function ledgerAggregateCandidate(l,remaining){let desc=norm(l.desc);if(!/charge|fee|fees|bank|amf|sms|commission|levy|vat|stamp|rtgs|remita|processing|tax/.test(desc))return null;let arr=remaining.filter(x=>feeLike(x.r.desc)&&gap(x.r.d,l.d)<=31);if(!arr.length)return null;let sum=arr.reduce((a,x)=>a+x.r.amt,0);return Math.abs(sum-l.amt)<.01?{items:arr,value:sum}:null}
function reversePairCandidate(items){for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++)if(Math.abs(items[i].r.amt+items[j].r.amt)<.01&&gap(items[i].r.d,items[j].r.d)<=7)return[i,j];return null}
async function run(){clearErr();let used=new Set(),ma=[],ti=[],un=[],n=S.bank.length;$('bar').style.width='0%';for(let i=0;i<n;i++){let b=S.bank[i],q=best(b,used);if(q.bi>=0){let l=S.ledger[q.bi],g=gap(b.d,l.d),ex=Math.abs(b.amt-l.amt)<.01;if(ex&&q.bs>=70){used.add(q.bi);let x={b,l,score:Math.round(q.bs),g};g===0?ma.push(x):g<=7?ti.push(x):un.push({src:'Bank',r:b,why:'Date difference outside timing window.'})}else un.push({src:'Bank',r:b,why:'Amount or match confidence is insufficient.'})}else un.push({src:'Bank',r:b,why:'No ledger candidate found.'});$('bar').style.width=Math.round((i+1)/n*100)+'%';if(i%10===0)await new Promise(r=>setTimeout(r,0))}
let ledgerUn=S.ledger.map((r,i)=>({r,i})).filter(x=>!used.has(x.i));
for(const x of ledgerUn){let remaining=un.filter(u=>u.src==='Bank');let ag=ledgerAggregateCandidate(x.r,remaining);if(ag){ag.items.forEach(item=>{let k=un.indexOf(item);if(k>=0)un.splice(k,1)});ag.items.forEach(item=>{let bi=S.bank.indexOf(item.r);if(bi>=0)used.add(bi)});used.add(x.i);ma.push({b:ag.items[0].r,l:x.r,score:100,g:0,aggregate:true,count:ag.items.length,value:ag.value})}}
let left=S.ledger.map((r,i)=>({r,i})).filter(x=>!used.has(x.i)),rp=reversePairCandidate(left);if(rp){let a=left[rp[0]],b=left[rp[1]];used.add(a.i);used.add(b.i);un.push({src:'Ledger',r:a.r,why:'Internal GL reversal pair — net effect is zero; review only if the entries should affect the bank.'});un.push({src:'Ledger',r:b.r,why:'Internal GL reversal pair — net effect is zero; review only if the entries should affect the bank.'})}
S.ledger.forEach((l,i)=>{if(!used.has(i))un.push({src:'Ledger',r:l,why:'No corresponding bank transaction found.'})});S.r={ma,ti,un};render()}
function render(){$('res').classList.remove('hidden');$('mc').textContent=S.r.ma.length;$('ec').textContent=S.r.ti.length+S.r.un.length;$('status').textContent='Reconciliation complete. Review exceptions before finalizing.';$('mb').innerHTML=S.r.ma.map(x=>`<tr><td>${fd(x.b.d)}</td><td>${fd(x.l.d)}</td><td>${money(x.value??x.b.amt)}</td><td>${esc(x.aggregate?(x.l.desc+' ('+x.count+' bank lines)'):x.b.desc)}</td><td><span class="pill match">${x.aggregate?'Aggregated':'Exact'}</span></td><td><span class="pill match">${x.score}%</span></td></tr>`).join('')||'<tr><td colspan="6">No matched transactions.</td></tr>';$('tb').innerHTML=S.r.ti.map(x=>`<tr><td>${fd(x.b.d)}</td><td>${fd(x.l.d)}</td><td>${money(x.b.amt)}</td><td>${esc(x.b.desc)}</td><td><span class="pill timing">Exact amount • ${x.g} day gap</span></td></tr>`).join('')||'<tr><td colspan="5">No timing differences.</td></tr>';$('ub').innerHTML=S.r.un.map(x=>`<tr><td>${x.src}</td><td>${fd(x.r.d)}</td><td>${money(x.r.amt)}</td><td>${esc(x.r.desc)}</td><td><span class="pill unmatched">${esc(x.why)}</span></td></tr>`).join('')||'<tr><td colspan="5">No unmatched transactions.</td></tr>';$('print').classList.remove('hidden');report()}
function report(){let bank=S.bank.reduce((a,x)=>a+x.amt,0),led=S.ledger.reduce((a,x)=>a+x.amt,0),v=bank-led,ub=S.r.un.filter(x=>x.src==='Bank'),ul=S.r.un.filter(x=>x.src==='Ledger'),net=ub.reduce((a,x)=>a+x.r.amt,0)-ul.reduce((a,x)=>a+x.r.amt,0),matched=S.r.ma.reduce((a,x)=>a+(x.value??x.b.amt),0),tim=S.r.ti.reduce((a,x)=>a+x.b.amt,0),t=new Date().toLocaleDateString('en-NG',{day:'2-digit',month:'short',year:'numeric'}),st=S.r.un.length===0?'RECONCILED':'REVIEW REQUIRED';$('report').innerHTML=`<div class="report-head"><h2>RECONAI</h2><h3>BANK RECONCILIATION STATEMENT</h3><div>Generated ${t}</div></div><h3>Control summary</h3><div class="tablewrap"><table><tr><th>Description</th><th class="right">Amount (₦)</th></tr><tr><td>Total bank transaction value</td><td class="right">${money(bank)}</td></tr><tr><td>Total ledger transaction value</td><td class="right">${money(led)}</td></tr><tr><td>Control variance</td><td class="right"><b>${money(v)}</b></td></tr><tr><td>Net unresolved difference</td><td class="right"><b>${money(net)}</b></td></tr></table></div><h3>Reconciling items</h3><div class="tablewrap"><table><tr><th>Category</th><th>Count</th><th class="right">Value (₦)</th></tr><tr><td>Matched / aggregated</td><td>${S.r.ma.length}</td><td class="right">${money(matched)}</td></tr><tr><td>Timing differences</td><td>${S.r.ti.length}</td><td class="right">${money(tim)}</td></tr><tr><td>Bank items not in GL</td><td>${ub.length}</td><td class="right">${money(ub.reduce((a,x)=>a+x.r.amt,0))}</td></tr><tr><td>GL items not in Bank</td><td>${ul.length}</td><td class="right">${money(ul.reduce((a,x)=>a+x.r.amt,0))}</td></tr></table></div><div class="${st==='RECONCILED'?'ok':'error'}"><b>Reconciliation status: ${st}</b><br>Control variance: <b>${money(v)}</b><br>Net unresolved difference: <b>${money(net)}</b><br>${st==='RECONCILED'?'All transactions are accounted for by exact, timing or approved aggregate matching.':'Review the exception schedule before finalizing.'}</div><h3>Exception schedule</h3><div class="tablewrap"><table><tr><th>Source</th><th>Date</th><th>Particulars</th><th class="right">Amount</th><th>Assessment</th></tr>${S.r.un.map(x=>`<tr><td>${x.src}</td><td>${fd(x.r.d)}</td><td>${esc(x.r.desc)}</td><td class="right">${money(x.r.amt)}</td><td>${esc(x.why)}</td></tr>`).join('')||'<tr><td colspan="5">No exceptions.</td></tr>'}</table></div><p>Prepared by: ____________________ &nbsp;&nbsp;&nbsp; Reviewed by: ____________________</p>`}
'''
s=s[:start]+new+s[end:]
p.write_text(s)
