(function(){
'use strict';
const moneyFmt=n=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:2}).format(Number(n)||0);
const dt=v=>{try{return v?new Date(v).toLocaleDateString('en-NG',{day:'2-digit',month:'short',year:'numeric'}):''}catch(e){return String(v??'')}};
const nsum=a=>(a||[]).reduce((s,x)=>s+(Number(x.amt)||0),0);
const sameDir=(a,b)=>Math.abs((Number(a)||0)-(Number(b)||0))<.01&&((a>=0&&b>=0)||(a<0&&b<0));
const textSim=(a,b)=>{let A=new Set(String(a||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').split(' ').filter(Boolean)),B=new Set(String(b||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').split(' ').filter(Boolean));if(!A.size||!B.size)return 0;let n=0;A.forEach(x=>B.has(x)&&n++);return n/Math.max(A.size,B.size)};
const dayGap=(a,b)=>{let x=new Date(a),y=new Date(b);return isNaN(x)||isNaN(y)?999:Math.round(Math.abs(x-y)/86400000)};
function markDirect(){let usedB=new Set(),usedL=new Set(),ma=[],ti=[];for(const b of S.bank||[]){let best=null;for(let i=0;i<(S.ledger||[]).length;i++){if(usedL.has(i))continue;let l=S.ledger[i];if(!sameDir(b.amt,l.amt))continue;let g=dayGap(b.d,l.d),rf=b.ref&&l.ref&&String(b.ref).trim().toLowerCase()===String(l.ref).trim().toLowerCase(),ds=textSim(b.desc,l.desc);let score=(g===0?35:g<=7?Math.max(0,21-g*3):0)+(rf?45:0)+ds*20;if(!best||score>best.score)best={i,l,g,score}}if(best&&best.score>=45){usedB.add(b.id);usedL.add(best.i);let x={b,l:best.l,score:Math.min(99,Math.round(best.score)),g:best.g};if(best.g===0)ma.push(x);else if(best.g<=7)ti.push(x);else{usedB.delete(b.id);usedL.delete(best.i)}}}return{usedB,usedL,ma,ti}}
function subset(items,target,maxN=6){let arr=items.filter(x=>sameDir(x.amt,target));if(!arr.length)return null;let best=null;function walk(start,chosen,total){if(Math.abs(total-target)<.01&&chosen.length){let score=chosen.reduce((s,x)=>s+textSim(x.desc,target._desc||'') ,0);best=best&&best.score>=score?best:{items:chosen.slice(),score};return}if(chosen.length>=maxN||start>=arr.length)return;for(let i=start;i<arr.length;i++){let n=total+arr[i].amt;if(Math.abs(n)>Math.abs(target.amt)*1.02+.01)continue;chosen.push(arr[i]);walk(i+1,chosen,n);chosen.pop()}}walk(0,[],0);return best}
function groupedMatch(unB,unL){let usedB=new Set(),usedL=new Set(),groups=[];
for(const l of unL){let avail=unB.filter(b=>!usedB.has(b.id));if(avail.length<2)continue;let target=Object.assign({},l,{_desc:l.desc});let q=subset(avail,target,6);if(q&&q.items.length>=2){let sim=q.items.reduce((s,b)=>s+textSim(b.desc,l.desc),0)/q.items.length;if(sim>=.12||q.items.every(b=>dayGap(b.d,l.d)<=7)){q.items.forEach(b=>usedB.add(b.id));usedL.add(l.id);groups.push({bs:q.items,ls:[l],basis:'One-to-many aggregate; same debit/credit direction and exact total'});}}
}
for(const b of unB.filter(x=>!usedB.has(x.id))){let avail=unL.filter(l=>!usedL.has(l.id));if(avail.length<2)continue;let target=Object.assign({},b,{_desc:b.desc});let q=subset(avail,target,6);if(q&&q.items.length>=2){let sim=q.items.reduce((s,l)=>s+textSim(l.desc,b.desc),0)/q.items.length;if(sim>=.12||q.items.every(l=>dayGap(b.d,l.d)<=7)){q.items.forEach(l=>usedL.add(l.id));usedB.add(b.id);groups.push({bs:[b],ls:q.items,basis:'Many-to-one aggregate; same debit/credit direction and exact total'});}}
}
return{groups,usedB,usedL}}
function reversalSet(rows){let used=new Set(),out=[];for(let i=0;i<rows.length;i++){if(used.has(rows[i].id))continue;for(let j=i+1;j<rows.length;j++){if(used.has(rows[j].id))continue;let a=rows[i],b=rows[j];if(Math.abs(a.amt+b.amt)<.01&&a.amt!==0&&dayGap(a.d,b.d)<=7&&(textSim(a.desc,b.desc)>=.12||(a.ref&&b.ref&&String(a.ref).toLowerCase()===String(b.ref).toLowerCase()))){used.add(a.id);used.add(b.id);out.push({a,b});break}}}return{used,out}}
function phase1Run(){let d=markDirect(),usedB=new Set(d.usedB),usedL=new Set(d.usedL),rb=reversalSet((S.bank||[]).filter(x=>!usedB.has(x.id))),rl=reversalSet((S.ledger||[]).filter(x=>!usedL.has(x.id)));rb.used.forEach(id=>usedB.add(id));rl.used.forEach(id=>usedL.add(id));let remB=(S.bank||[]).filter(x=>!usedB.has(x.id)),remL=(S.ledger||[]).filter(x=>!usedL.has(x.id));let g=groupedMatch(remB,remL);g.usedB.forEach(id=>usedB.add(id));g.usedL.forEach(id=>usedL.add(id));S.r={ma:d.ma,ti:d.ti,grouped:g.groups,reversals:[...rb.out,...rl.out],unB:(S.bank||[]).filter(x=>!usedB.has(x.id)),unL:(S.ledger||[]).filter(x=>!usedL.has(x.id))};if(typeof render==='function')render();else if(typeof buildStatement==='function')buildStatement()}
function clean(){let r=S.r||{};return{ma:r.ma||[],ti:r.ti||[],grouped:r.grouped||[],reversals:r.reversals||[],unB:r.unB||[],unL:r.unL||[]}}
function statement(){let r=clean(),b=S.bank||[],l=S.ledger||[];let opening=l.length&&l[0].balance!==null?l[0].balance:null;let glDeb=l.reduce((a,x)=>a+(Number(x.debit)||0),0),glCre=l.reduce((a,x)=>a+(Number(x.credit)||0),0);let glClose=opening!==null?opening+glCre-glDeb:nsum(l);let timingB=r.ti.map(x=>x.b),timingL=r.ti.map(x=>x.l);let creditB=r.unB.filter(x=>x.amt>0),debitB=r.unB.filter(x=>x.amt<0),creditL=r.unL.filter(x=>x.amt>0),debitL=r.unL.filter(x=>x.amt<0);let fee=/\b(vat|nip|stamp|processing|charge|charges|fee|fees|sms notification|rtgs|remita|commission|amf|levy|tax|emtl|emt|bank charge)\b/i;let bankCharges=debitB.filter(x=>fee.test(String(x.desc||'')));let debitBankOther=debitB.filter(x=>!fee.test(String(x.desc||'')));let bankClosing=[...b].reverse().find(x=>x.balance!==null&&x.balance!==undefined)?.balance;let confirmed=bankClosing!==undefined?bankClosing:nsum(b);let adjCredit=Math.abs(nsum(creditL))+Math.abs(nsum(creditB)),adjDebit=Math.abs(nsum(debitL))+Math.abs(nsum(debitBankOther))+Math.abs(nsum(bankCharges));let timingNet=nsum(timingB);let computed=glClose+adjCredit-adjDebit+timingNet;return{r,b,l,opening,glDeb,glCre,glClose,creditB,debitB,creditL,debitL,bankCharges,debitBankOther,timingB,timingL,confirmed,computed,variance:computed-confirmed}}
function build(){let d=statement();let line=(x)=>`${dt(x.d)} — ${x.desc||x.ref||'Unspecified transaction'}`;let section=(title,rows)=>`<table><tr><th colspan="2">${title}</th></tr>${rows.length?rows.map(x=>`<tr><td>${esc(line(x))}</td><td class="amount">${moneyFmt(Math.abs(x.amt))}</td></tr>`).join(''):'<tr><td>(none)</td><td class="amount">0.00</td></tr>'}<tr class="total"><td>Total</td><td class="amount">${moneyFmt(Math.abs(nsum(rows)))}</td></tr></table>`;
$('report').innerHTML=`<div class="working"><div class="title"><h1>BANK RECONCILIATION STATEMENT</h1><h2>Chorus Energy Limited</h2><div>Period: ${(d.b||[]).length?dt(Math.min(...d.b.map(x=>new Date(x.d).getTime())))+' to '+dt(Math.max(...d.b.map(x=>new Date(x.d).getTime()))):''}</div></div><div class="section">BALANCE PER GENERAL LEDGER</div><table><tr><th>Particulars</th><th class="amount">Amount (₦)</th></tr><tr><td>Balance as per GL - Opening</td><td class="amount">${d.opening===null?'—':moneyFmt(d.opening)}</td></tr><tr><td>Add: Ledger Credits</td><td class="amount">${moneyFmt(d.glCre)}</td></tr><tr><td>Less: Ledger Debits</td><td class="amount">(${moneyFmt(d.glDeb).replace('₦','')})</td></tr><tr class="shade"><td>Balance as per GL - Closing</td><td class="amount">${moneyFmt(d.glClose)}</td></tr></table><div class="section">RECONCILING ITEMS — ADD</div>${section('Credit items in Ledger but not in Bank',d.creditL)}${section('Credit items in Bank but not in Ledger',d.creditB)}<div class="section">RECONCILING ITEMS — LESS</div>${section('Debit items in Ledger but not in Bank',d.debitL)}${section('Debit items in Bank but not in Ledger',d.debitBankOther)}${section('Bank Charges',d.bankCharges)}${d.timingB.length?section('Timing Differences — included as reconciling items',d.timingB):''}<div class="section">FINAL RECONCILIATION</div><table><tr class="shade"><td><b>Adjusted balance as per Bank Statement</b></td><td class="amount"><b>${moneyFmt(d.computed)}</b></td></tr><tr><td>Bank Statement Closing Balance</td><td class="amount"><b>${moneyFmt(d.confirmed)}</b></td></tr><tr><td class="variance">Variance</td><td class="amount variance ${Math.abs(d.variance)<.01?'reconciled':''}">${moneyFmt(d.variance)}</td></tr><tr><td><b>Reconciliation status</b></td><td class="amount"><b>${Math.abs(d.variance)<.01?'RECONCILED':'REVIEW REQUIRED'}</b></td></tr></table><div class="memo">Direct matched items, grouped matches and reversal items are excluded from this statement and remain in their designated sections. Timing differences remain in Timing Differences and are also included above as reconciling items.</div><div class="signature">Prepared by: __________________________ &nbsp;&nbsp;&nbsp; Reviewed by: __________________________</div></div>`}
function exportExcel(){let r=clean(),d=statement(),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['BANK RECONCILIATION STATEMENT'],['Balance per GL',d.glClose],['Adjusted Bank Balance',d.computed],['Bank Closing Balance',d.confirmed],['Variance',d.variance]]),'Reconciliation Statement');let m=[['Bank Date','Ledger Date','Amount','Description','Confidence']];r.ma.forEach(x=>m.push([dt(x.b.d),dt(x.l.d),x.b.amt,x.b.desc,x.score+'%']));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(m),'Matched');let t=[['Bank Date','Ledger Date','Amount','Description','Reason']];r.ti.forEach(x=>t.push([dt(x.b.d),dt(x.l.d),x.b.amt,x.b.desc,'Timing difference']));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(t),'Timing Differences');let g=[['Bank Items','Ledger Items','Bank Total','Ledger Total','Basis']];r.grouped.forEach(x=>g.push([x.bs.length,x.ls.length,nsum(x.bs),nsum(x.ls),x.basis]));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(g),'Grouped Matches');let rv=[['Date','Amount','Entry A','Entry B','Assessment']];r.reversals.forEach(x=>rv.push([dt(x.a.d),Math.abs(x.a.amt),x.a.desc,x.b.desc,'Reversal']));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rv),'Reversals');let ex=[['Source','Date','Amount','Description','Debit/Credit']];r.unB.forEach(x=>ex.push(['Bank',dt(x.d),x.amt,x.desc,x.amt>=0?'Credit':'Debit']));r.unL.forEach(x=>ex.push(['Ledger',dt(x.d),x.amt,x.desc,x.amt>=0?'Credit':'Debit']));XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(ex),'Exceptions');XLSX.writeFile(wb,'ReconAI_Bank_Reconciliation_'+new Date().toISOString().slice(0,10)+'.xlsx')}
async function exportPdf(){let d=statement();if(!(window.jspdf&&window.jspdf.jsPDF))await new Promise((ok,no)=>{let s=document.createElement('script');s.src='https://unpkg.com/jspdf@4.0.0/dist/jspdf.umd.min.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)});let doc=new jspdf.jsPDF({orientation:'portrait',unit:'mm',format:'a4'});doc.html($('report'),{callback:pdf=>pdf.save('ReconAI_Bank_Reconciliation_'+new Date().toISOString().slice(0,10)+'.pdf'),x:8,y:8,width:194,windowWidth:980})}
function install(){if(!$('results'))return;let p=$('statementPanel'),rpt=$('report');if(!rpt)return;let old=document.getElementById('phase1-toolbar');if(old)old.remove();let bar=document.createElement('div');bar.id='phase1-toolbar';bar.className='export-toolbar';bar.innerHTML='<button type="button" class="export-btn export-excel">Download Excel</button><button type="button" class="export-btn export-pdf">Download PDF</button>';rpt.prepend(bar);bar.querySelector('.export-excel').onclick=exportExcel;bar.querySelector('.export-pdf').onclick=exportPdf}
window.buildStatement=build;window.phase1Run=phase1Run;window.phase1Install=install;
if(typeof $==='function'&&$('go'))$('go').onclick=phase1Run;
new MutationObserver(()=>setTimeout(install,0)).observe($('report'),{childList:true,subtree:false});
})();